import Head from "next/head";
import Image from "next/image";
import logoLapor from "../public/img/logo-lapor.png";

import Parser from "rss-parser";
let parser = new Parser();

const getFeed = async () => {
  try {
    let feed = await parser.parseURL('https://berita.murungrayakab.go.id/');
    console.log(feed);
  } catch(e) {
    console.log(e.message);
  }
}

getFeed();

(async () => {
  let parser = new Parser();
  let feed = await parser.parseURL('https://berita.murungrayakab.go.id/')
  console.log(feed);
})();

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portal Kabupaten Murung Raya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo-mura.png" />
      </Head>

      <div className="flex px-8 py-3 bg-navy-50">
        <div className="font-sans text-sm text-white">Portal Kabupaten Murung Raya</div>
      </div>

      <div className="flex items-center justify-between px-16 py-6 pt-8 bg-navy-200">
        <div className="font-sans text-white">Beranda</div>
        <div className="font-sans text-white">Pencarian</div>
      </div>

      <div className="flex items-center justify-center font-sans bg-gray-100 min-h-fit">
        <div className="max-w-xl">
          <div className="bg-white shadow-sm rounded-xl">
            <header className="px-4 py-2 border-b 5">Selamat Datang</header>
          </div>
        </div>
      </div>

      <div>
        
      </div>

      <div className="flex items-center justify-between max-h-screen px-8 pb-4 font-sans bg-gray-100">
        <div className="max-w-xl">
          <div className="overflow-hidden bg-white shadow-sm rounded-xl">
            <div className="px-4 py-2.5 border-b bg-gray-50/50">
              <h1 className="font-medium">
                Layanan Publik
              </h1>
            </div>
            <div className="px-4 py-2.5">Layanan Perizinan (DPMPTSP)</div>
            <div className="px-4 py-2.5">
              <Image
                src={logoLapor}
                alt="Logo Lapor"
              />
              <div><a href="https://www.lapor.go.id/" target="_blank">Layanan Pengadaan Laporan Aspirasi dan</a></div>
            </div>
            <div className="px-4 py-2.5">Pengaduan Online Rakyat</div>
            <div className="px-4 py-2.5">Aplikasi Pengaduan dan Aspirasi (SAPA)</div>
          </div>
        </div>
      </div>

      <div>
        <div>Pemerintahan</div>
      </div>

      <div>
        <div>Perangkat Daerah</div>
        <p>
          SETDA, INSP, SETWAN, DISDIKBUD, SATPOL PP DAMKAR, DISSOS, DISDALDUL
          KBP3A, DLH, DISDUKCAPIL, DPMD <br />
          DISPERINDAGKOP UKM, DPMPTSP, DISPARPORA, DISARPUS, DISHUB, DISKES,
          DISNAKERTRANS, DIS PUPR, DIS PKPP, DISHANPANG <br />
          DISTANIK, DISKOMINFO SP, BAPPELITBANGDA, BPKAD, BAPENDA, BKPSDM, BPBD,
          BAKESBANGPOL, RSUD
        </p>
      </div>

      <div className="px-5 py-6 mt-4 bg-navy-50">
        <div className="ml-12 font-sans text-neutral-500 sm:text-neutral-400">
          &copy; 2018-2022 | Dikelola oleh TIM Pengembangan e-Government
          DISKOMINFO SP Pemerintah Kabupaten Murung Raya.
        </div>
      </div>
    </div>
  );
}
